<a href="https://colab.research.google.com/github/Aicha-Nac/convolu-ao-discreta-python/blob/main/01_representacao_sinais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SINAIS DISCRETOS

In [4]:
import numpy as np


In [5]:
x=[1,0,3,2]
h=[1,1,1]
def convolve_direct(x, h):
    N = len(x)
    M = len(h)
    L = N+M-1
    y = np.zeros(L)

    for n in range(L):
        soma = 0
        for k in range(N):
            idx_h = n-k
            if 0 <= idx_h < M:
                soma = soma + x[k] * h[idx_h]
        y[n] = soma

    return y

y = convolve_direct(x, h)
print(y)

y_numpy = np.convolve(x, h)
print(y_numpy)
print(np.allclose(y, y_numpy))

x2 = np.array([2, 4, -1, 5, 3, 0, 7])   # N=7
h2 = np.array([1, -1])                   # M=2

y2 = convolve_direct(x2, h2)
y2_numpy = np.convolve(x2, h2)

print(y2)
print(y2_numpy)
print(np.allclose(y2, y2_numpy))

[1. 1. 4. 5. 5. 2.]
[1 1 4 5 5 2]
True
[ 2.  2. -5.  6. -2. -3.  7. -7.]
[ 2  2 -5  6 -2 -3  7 -7]
True


In [6]:
L = 6   # só um número de exemplo
contador = 0
for n in range(L):
    contador += 1
print("o laço rodou", contador, "vezes")

o laço rodou 6 vezes


In [7]:
import time

for N in [500, 1000, 2000]:
    x_teste = np.random.randn(N)
    h_teste = np.random.randn(N)

    inicio = time.perf_counter()
    y_teste = convolve_direct(x_teste, h_teste)
    fim = time.perf_counter()

    print(f"N={N} -> tempo: {fim - inicio:.4f} segundos")

N=500 -> tempo: 0.1089 segundos
N=1000 -> tempo: 0.4513 segundos
N=2000 -> tempo: 1.7648 segundos


In [8]:
!pip install numba -q
from numba import njit

@njit
def convolve_direct_numba(x, h):
    N = len(x)
    M = len(h)
    L = N + M - 1
    y = np.zeros(L)
    for n in range(L):
        soma = 0.0
        for k in range(N):
            idx_h = n - k
            if 0 <= idx_h < M:
                soma = soma + x[k] * h[idx_h]
        y[n] = soma
    return y

In [9]:
x = np.array([1, 0, 3, 2], dtype=float)
h = np.array([1, 1, 1], dtype=float)

y_numpy = np.convolve(x, h)
y_nb = convolve_direct_numba(x, h)

print(y_nb)
print(np.allclose(y_nb, y_numpy))

[1. 1. 4. 5. 5. 2.]
True


In [12]:
import time

# warm-up: a primeira chamada inclui tempo de compilação, não conta
convolve_direct_numba(np.random.randn(10), np.random.randn(10))

print("Sem Numba (convolve_direct)")
for N in [500, 1000, 2000]:
    x_teste = np.random.randn(N)
    h_teste = np.random.randn(N)
    inicio = time.perf_counter()
    convolve_direct(x_teste, h_teste)
    fim = time.perf_counter()
    print(f"N={N} -> tempo: {fim - inicio:.6f} segundos")

print( "Com Numba (convolve_direct_numba)")
for N in [500, 1000, 2000]:
    x_teste = np.random.randn(N)
    h_teste = np.random.randn(N)
    inicio = time.perf_counter()
    convolve_direct_numba(x_teste, h_teste)
    fim = time.perf_counter()
    print(f"N={N} -> tempo: {fim - inicio:.6f} segundos")

Sem Numba (convolve_direct)
N=500 -> tempo: 0.301145 segundos
N=1000 -> tempo: 0.445242 segundos
N=2000 -> tempo: 1.799809 segundos
Com Numba (convolve_direct_numba)
N=500 -> tempo: 0.000479 segundos
N=1000 -> tempo: 0.001834 segundos
N=2000 -> tempo: 0.007424 segundos


In [1]:
!nvidia-smi

Sun Sep 13 00:41:47 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import numpy as np
import time

def convolve_direct(x, h):
    N = len(x)
    M = len(h)
    L = N + M - 1
    y = np.zeros(L)
    for n in range(L):
        soma = 0
        for k in range(N):
            idx_h = n - k
            if 0 <= idx_h < M:
                soma = soma + x[k] * h[idx_h]
        y[n] = soma
    return y

!pip install numba -q
from numba import njit

@njit
def convolve_direct_numba(x, h):
    N = len(x)
    M = len(h)
    L = N + M - 1
    y = np.zeros(L)
    for n in range(L):
        soma = 0.0
        for k in range(N):
            idx_h = n - k
            if 0 <= idx_h < M:
                soma = soma + x[k] * h[idx_h]
        y[n] = soma
    return y

x = np.array([1, 0, 3, 2], dtype=float)
h = np.array([1, 1, 1], dtype=float)
convolve_direct_numba(np.random.randn(10), np.random.randn(10))  # warm-up

print("tudo recriado, pronto pra continuar")

tudo recriado, pronto pra continuar


In [3]:
import cupy as cp

# Teste de corretude: comparar convolução na GPU com numpy (CPU)
x_gpu = cp.asarray(x)
h_gpu = cp.asarray(h)
y_cupy = cp.convolve(x_gpu, h_gpu)

y_numpy = np.convolve(x, h)

print("CuPy: ", cp.asnumpy(y_cupy))
print("numpy:", y_numpy)
print("Bateu?", np.allclose(cp.asnumpy(y_cupy), y_numpy))

CuPy:  [1. 1. 4. 5. 5. 2.]
numpy: [1. 1. 4. 5. 5. 2.]
Bateu? True


In [4]:
import time

# warm-up (a primeira chamada inclui overhead de inicializar a GPU)
x_warmup = cp.random.randn(10)
h_warmup = cp.random.randn(10)
cp.convolve(x_warmup, h_warmup)
cp.cuda.Stream.null.synchronize()

print(" Com CuPy (GPU)")
for N in [500, 1000, 2000]:
    x_teste = cp.random.randn(N)
    h_teste = cp.random.randn(N)

    cp.cuda.Stream.null.synchronize()  # garante que o que veio antes já terminou
    inicio = time.perf_counter()
    y_gpu = cp.convolve(x_teste, h_teste)
    cp.cuda.Stream.null.synchronize()  # espera a GPU terminar de verdade
    fim = time.perf_counter()

    print(f"N={N} -> tempo: {fim - inicio:.6f} segundos")

=== Com CuPy (GPU) ===
N=500 -> tempo: 0.113378 segundos
N=1000 -> tempo: 0.186600 segundos
N=2000 -> tempo: 0.057291 segundos


In [3]:
print(" numpy.convolve (biblioteca pronta)")
for N in [500, 1000, 2000]:
    x_teste = np.random.randn(N)
    h_teste = np.random.randn(N)
    inicio = time.perf_counter()
    np.convolve(x_teste, h_teste)
    fim = time.perf_counter()
    print(f"N={N} -> tempo: {fim - inicio:.6f} segundos")

=== numpy.convolve (biblioteca pronta) ===
N=500 -> tempo: 0.000198 segundos
N=1000 -> tempo: 0.000317 segundos
N=2000 -> tempo: 0.001088 segundos
